### ISSUE TITLE
[k8s] Fail to launch cluster on kubernetes within docker container

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#2626] opened 2023-09-29 06:01 UTC
I have a GKE cluster, and it works smoothly to `sky launch` a cluster in bash, but when I try to launch a cluster in a docker container with `--net=host`, the ssh jump seems not working.

To reproduce:
1. `docker run -it --net=host --name skypilot-debug berkeleyskypilot/skypilot-debug /bin/bash`
2. `gcloud container clusters get-credentials cluster-name --region us-central1-c`
3. `sky check; sky launch --gpus T4`

The following logs keep showing in the `provision.log`
```
2023-09-29 05:05:15,896 INFO updater.py:312 -- SSH still not available ^[[2m(SSH command failed.)^[[22m^[[26m, retrying in ^[[1m5^[[22m^[[26m seconds.
2023-09-29 05:05:20,905 VINFO command_runner.py:371 -- Running `^[[1muptime^[[22m^[[26m`
2023-09-29 05:05:20,905 VVINFO command_runner.py:373 -- Full command is `^[[1mssh -tt -i ~/.ssh/sky-key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_63a9f0ea7b/e28b271989/%C -o ControlPersist=10s -o ProxyCommand=ssh -tt -i ~/.ssh/sky-key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -p 23100 -W %h:%p sky@127.0.0.1 -o ProxyCommand='/root/.sky/port-forward-proxy-cmd.sh'  -o Port=22 -o ConnectTimeout=10s sky@10.124.0.17 bash --login -c -i 'source ~/.bashrc; export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'^[[22m^[[26m`
Connection timed out during banner exchange^M
Connection to UNKNOWN port 65535 timed out^M
2023-09-29 05:05:30,920 INFO updater.py:312 -- SSH still not available ^[[2m(SSH command failed.)^[[22m^[[26m, retrying in ^[[1m5^[[22m^[[26m seconds.
2023-09-29 05:05:35,930 VINFO command_runner.py:371 -- Running `^[[1muptime^[[22m^[[26m`
2023-09-29 05:05:35,930 VVINFO command_runner.py:373 -- Full command is `^[[1mssh -tt -i ~/.ssh/sky-key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_63a9f0ea7b/e28b271989/%C -o ControlPersist=10s -o ProxyCommand=ssh -tt -i ~/.ssh/sky-key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -p 23100 -W %h:%p sky@127.0.0.1 -o ProxyCommand='/root/.sky/port-forward-proxy-cmd.sh'  -o Port=22 -o ConnectTimeout=10s sky@10.124.0.17 bash --login -c -i 'source ~/.bashrc; export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'^[[22m^[[26m`
Connection timed out during banner exchange^M
Connection to UNKNOWN port 65535 timed out^M
2023-09-29 05:05:45,944 INFO updater.py:312 -- SSH still not available ^[[2m(SSH command failed.)^[[22m^[[26m, retrying in ^[[1m5^[[22m^[[26m seconds.
2023-09-29 05:05:50,953 VINFO command_runner.py:371 -- Running `^[[1muptime^[[22m^[[26m`
2023-09-29 05:05:50,953 VVINFO command_runner.py:373 -- Full command is `^[[1mssh -tt -i ~/.ssh/sky-key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_63a9f0ea7b/e28b271989/%C -o ControlPersist=10s -o ProxyCommand=ssh -tt -i ~/.ssh/sky-key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -p 23100 -W %h:%p sky@127.0.0.1 -o ProxyCommand='/root/.sky/port-forward-proxy-cmd.sh'  -o Port=22 -o ConnectTimeout=10s sky@10.124.0.17 bash --login -c -i 'source ~/.bashrc; export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'^[[22m^[[26m`
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
```

**Comment by romilbhardwaj** [comment] 2023-10-16 01:45
After offline discussion, looks like this was being caused by netcat (`nc`) not being installed in the docker image. Debugged by running the ssh command manually with `-vvv` flag, which showed `nc: command not found`. Can be fixed by:

```
apt update
apt install netcat
```

But this indeed something our dependency checks should catch and raise early like we do for socat(rather than failing silently). Should also be covered in the docs.

**Closed** 2023-10-16 04:23 UTC
Labels: P0, k8s
