### ISSUE TITLE
Sky spot job failure due to sqlite3 database lock

### ISSUE THREAD

**Issue by lhqing** [skypilot-org/skypilot#1507] opened 2022-12-10 03:02 UTC
Hi Sky team,

**Cloud:**
GCP

**Sky version:**
most up-to-date from github

**Problem:**
My spot job continuously being interrupted and recovered by the sky controller, the `sky logs CONTROLER_NAME JOB_ID` seems to show a `sqlite3.OperationalError`. This error is recurring (**but not always**) when submitting the SKY YAML attached below, logs is also attached.

**Sky yaml:**
```
resources:
  cloud: gcp
  instance_type: n2d-highcpu-96
  region: us-west1
  image_id: projects/ecker-bican/global/images/bican-mm10-hisat-3n-mapping
  disk_size: 384

setup: |
  yap --version
  allcools --version
  hisat-3n --version
  pip install gcsfs
  pip install git+https://github.com/lhqing/gliderport.git
  pip install --upgrade cemba_data
  pip install --upgrade allcools

run: |
  ...
  # My computation code, which is cpu intensive, and in the beginning I/O intensive, 
  # but should not have any interaction with sky's files. Disk space is enough, memory is normal
```

**Sky command**
`sky spot launch -y -d -n job_name spot.yaml --retry-until-up`

Full log file: [failed.log](https://github.com/skypilot-org/skypilot/files/10199079/failed.log)

Error info in the log:
```
(worker-map-devel2-test-0, pid=9272) I 12-10 02:41:34 recovery_strategy.py:156] Spot cluster launched.
(worker-map-devel2-test-0, pid=9272) I 12-10 02:41:42 spot_utils.py:64] === Checking the job status... ===
(worker-map-devel2-test-0, pid=9272) I 12-10 02:41:46 spot_utils.py:70] Job status: JobStatus.RUNNING
(worker-map-devel2-test-0, pid=9272) I 12-10 02:41:46 spot_utils.py:73] ==================================
(worker-map-devel2-test-0, pid=9272) I 12-10 02:41:49 spot_state.py:124] Job started.
(worker-map-devel2-test-0, pid=9272) I 12-10 02:42:10 spot_utils.py:64] === Checking the job status... ===
(worker-map-devel2-test-0, pid=9272) I 12-10 02:42:14 spot_utils.py:70] Job status: JobStatus.RUNNING
(worker-map-devel2-test-0, pid=9272) I 12-10 02:42:14 spot_utils.py:73] ==================================
(worker-map-devel2-test-0, pid=9272) I 12-10 02:42:35 spot_utils.py:64] === Checking the job status... ===
(worker-map-devel2-test-0, pid=9272) E 12-10 02:42:46 subprocess_utils.py:70] Traceback (most recent call last):
(worker-map-devel2-test-0, pid=9272) E 12-10 02:42:46 subprocess_utils.py:70]   File "<string>", line 1, in <module>
(worker-map-devel2-test-0, pid=9272) E 12-10 02:42:46 subprocess_utils.py:70]   File "/home/hanliu_salk_edu/mambaforge/lib/python3.8/site-packages/sky/__init__.py", line 10, in <module>
(worker-map-devel2-test-0, pid=9272) E 12-10 02:42:46 subprocess_utils.py:70]     from sky import backends
(worker-map-devel2-test-0, pid=9272) E 12-10 02:42:46 subprocess_utils.py:70]   File "/home/hanliu_salk_edu/mambaforge/lib/python3.8/site-packages/sky/backends/__init__.py", line 3, in <module>
(worker-map-devel2-test-0, pid=9272) E 12-10 02:42:46 subprocess_utils.py:70]     from sky.backends.cloud_vm_ray_backend import CloudVmRayBackend
(worker-map-devel2-test-0, pid=9272) E 12-10 02:42:46 subprocess_utils.py:70]   File "/home/hanliu_salk_edu/mambaforge/lib/python3.8/site-packages/sky/backends/cloud_vm_ray_backend.py", line 38, in <module>
(worker-map-devel2-test-0, pid=9272) E 12-10 02:42:46 subprocess_utils.py:70]     from sky.skylet import autostop_lib
(worker-map-devel2-test-0, pid=9272) E 12-10 02:42:46 subprocess_utils.py:70]   File "/home/hanliu_salk_edu/mambaforge/lib/python3.8/site-packages/sky/skylet/autostop_lib.py", line 9, in <module>
(worker-map-devel2-test-0, pid=9272) E 12-10 02:42:46 subprocess_utils.py:70]     from sky.skylet import configs
(worker-map-devel2-test-0, pid=9272) E 12-10 02:42:46 subprocess_utils.py:70]   File "/home/hanliu_salk_edu/mambaforge/lib/python3.8/site-packages/sky/skylet/configs.py", line 26, in <module>
(worker-map-devel2-test-0, pid=9272) E 12-10 02:42:46 subprocess_utils.py:70]     c.execute("""\
(worker-map-devel2-test-0, pid=9272) E 12-10 02:42:46 subprocess_utils.py:70] sqlite3.OperationalError: database is locked
(worker-map-devel2-test-0, pid=9272) E 12-10 02:42:46 subprocess_utils.py:70]
(worker-map-devel2-test-0, pid=9272) I 12-10 02:42:46 spot_utils.py:72] Failed to connect to the cluster.
(worker-map-devel2-test-0, pid=9272) I 12-10 02:42:46 spot_utils.py:73] ==================================
(worker-map-devel2-test-0, pid=9272) I 12-10 02:42:56 controller.py:144] Failed to fetch the job status while the cluster is healthy. Try to recover the job (the cluster will not be restarted).
(worker-map-devel2-test-0, pid=9272) I 12-10 02:42:56 spot_state.py:134] === Recovering... ===
(worker-map-devel2-test-0, pid=9272) E 12-10 02:43:05 subprocess_utils.py:70] Traceback (most recent call last):
(worker-map-devel2-test-0, pid=9272) E 12-10 02:43:05 subprocess_utils.py:70]   File "<string>", line 1, in <module>
(worker-map-devel2-test-0, pid=9272) E 12-10 02:43:05 subprocess_utils.py:70]   File "/home/hanliu_salk_edu/mambaforge/lib/python3.8/site-packages/sky/__init__.py", line 10, in <module>
(worker-map-devel2-test-0, pid=9272) E 12-10 02:43:05 subprocess_utils.py:70]     from sky import backends
(worker-map-devel2-test-0, pid=9272) E 12-10 02:43:05 subprocess_utils.py:70]   File "/home/hanliu_salk_edu/mambaforge/lib/python3.8/site-packages/sky/backends/__init__.py", line 3, in <module>
(worker-map-devel2-test-0, pid=9272) E 12-10 02:43:05 subprocess_utils.py:70]     from sky.backends.cloud_vm_ray_backend import CloudVmRayBackend
(worker-map-devel2-test-0, pid=9272) E 12-10 02:43:05 subprocess_utils.py:70]   File "/home/hanliu_salk_edu/mambaforge/lib/python3.8/site-packages/sky/backends/cloud_vm_ray_backend.py", line 38, in <module>
(worker-map-devel2-test-0, pid=9272) E 12-10 02:43:05 subprocess_utils.py:70]     from sky.skylet import autostop_lib
(worker-map-devel2-test-0, pid=9272) E 12-10 02:43:05 subprocess_utils.py:70]   File "/home/hanliu_salk_edu/mambaforge/lib/python3.8/site-packages/sky/skylet/autostop_lib.py", line 9, in <module>
(worker-map-devel2-test-0, pid=9272) E 12-10 02:43:05 subprocess_utils.py:70]     from sky.skylet import configs
(worker-map-devel2-test-0, pid=9272) E 12-10 02:43:05 subprocess_utils.py:70]   File "/home/hanliu_salk_edu/mambaforge/lib/python3.8/site-packages/sky/skylet/configs.py", line 26, in <module>
(worker-map-devel2-test-0, pid=9272) E 12-10 02:43:05 subprocess_utils.py:70]     c.execute("""\
(worker-map-devel2-test-0, pid=9272) E 12-10 02:43:05 subprocess_utils.py:70] sqlite3.OperationalError: database is locked
(worker-map-devel2-test-0, pid=9272) E 12-10 02:43:05 subprocess_utils.py:70]
(worker-map-devel2-test-0, pid=9272) I 12-10 02:43:05 recovery_strategy.py:126] Ignoring the job cancellation failure; the spot cluster is likely completely stopped.
(worker-map-devel2-test-0, pid=9272) I 12-10 02:43:05 recovery_strategy.py:126]   Detailed exception: Command python3 -u -c 'import os;from sky.skylet import job_lib, log_lib;job_lib.cancel_jobs('"'"'hanliu_salk_edu'"'"',None)' failed with return code 1.
(worker-map-devel2-test-0, pid=9272) I 12-10 02:43:05 recovery_strategy.py:126] Failed to cancel jobs on cluster worker-map-devel2-test-0-2.
```

**Comment by concretevitamin** [comment] 2022-12-10 04:26
Thanks for the report @lhqing. We have a branch (https://github.com/skypilot-org/skypilot/tree/sqlite) that tries to address this problem. However, due to no reliable reproduction we were not sure whether it'll fix the problem.

Is it possible for you to try out that branch? I do see that you mentioned the "database is locked" does not always happen.

cc @lhqing

**Comment by lhqing** [comment] 2022-12-10 04:44
@concretevitamin Thanks, I will give it a try with dozens of jobs during the weekend, will report later

**Comment by lhqing** [comment] 2022-12-10 17:37
I tried another job with the same YAML, but using the sqlite branch. However, the database locked issue still happened after ~25 mins of normal running. The VM is then recovered.

`sky logs` file:
[database_lock.log](https://github.com/skypilot-org/skypilot/files/10200601/database_lock.log)

Git HEAD
```
commit 4192200dc7787e529939c9f60e4e692704101ae9 (HEAD -> sqlite, origin/sqlite)
Merge: e66d281 d7e777f
Author: Zongheng Yang <zongheng.y@gmail.com>
Date:   Sat Dec 10 12:28:23 2022 +0800
```

**Comment by Michaelvll** [comment] 2022-12-10 18:57
Thank you for trying it out! It seems the problem is caused by the lock for the autostop config database added in #1458. For that database, we already applied to fix from the sqlite branch, but it seems the problem still occurs. I am trying to reproduce the problem with a minimal snippet. Please stay tuned. : )

**Comment by Michaelvll** [comment] 2022-12-10 22:33
Hey @lhqing, we found a possible solution to your problem. Do you mind switching the `fix-db-locked` branch and having a try again?

**Comment by Michaelvll** [comment] 2022-12-13 23:21
#1590 should have solved this issue. I am going to close this issue for now. Please feel free to re-open it if the problem happens again. : )

**Closed by Michaelvll** 2022-12-13 23:21 UTC
