### ISSUE TITLE
[Storage] Suprising behavior when switching from MOUNT to COPY mode

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#786] opened 2022-05-02 23:47 UTC
I have a task with the following yaml, which works fine with the default MOUNT mode:
```
file_mounts:
  /imagenet:
    name: imagenet-bucket
```
However, when I added `mode: COPY` to copy the data to the disk, it raises the following error, which is a bit surprising to me. `sky.exceptions.StorageSourceError: Storage source must be specified when using COPY mode.`

Do you think we can allow this @romilbhardwaj ?
```
file_mounts:
  /imagenet:
    name: imagenet-bucket
    mode: COPY
```

**Comment by romilbhardwaj** [comment] 2022-10-31 10:57
Duplicate of #856, closed with #881.

**Closed by romilbhardwaj** 2022-10-31 10:57 UTC
Labels: enhancement
