### ISSUE TITLE
Consider replacing use of `pickle` in `global_user_state` and elsewhere

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#1605] opened 2023-01-18 17:45 UTC
User added a new field to `Resources` and then switched branch, as expected some errors happened:
```
  File "/opt/conda/envs/xxx/lib/python3.7/site-packages/sky/global_user_state.py", line 248, in get_handle_from_cluster_name
    return pickle.loads(handle)
AttributeError: Can't get attribute 'OS' on <module 'sky.clouds.cloud' from '/opt/conda/envs/xxx/lib/python3.7/site-packages/sky/clouds/cloud.py'>
```
User also mentioned:
> if sky code is ever refactored e.g. moving sky.cloud.Cloud to somewhere else, I think the pickle data would also break

Using a more flexible serde, maybe `json`, may fix this.

**Comment by romilbhardwaj** [comment] 2023-02-03 01:02
Related comment from @dongreenberg:

> I’ve gotten in the habit that any time I need to upgrade skypilot I totally uninstall and delete my ~/.sky directory. For some reason I’ve always had trouble if I don’t - exceptions that raise because of some malformed data or API expecting different input or something. I’m not sure if you guys do this too but I found it to be necessary for every upgrade I’ve done so far

**Comment by concretevitamin** [comment] 2023-02-27 17:37
Ran into this again after upgrading from python 3.7 to 3.8 in a new conda environment. `sky status` would fail at `pickle.loads()` due to version mismatch:
```
...
  File "/Users/zongheng/anaconda/envs/py38/lib/python3.8/site-packages/sky/backends/backend_utils.py", line 2244, in get_clusters
    records = global_user_state.get_clusters()
  File "/Users/zongheng/anaconda/envs/py38/lib/python3.8/site-packages/sky/global_user_state.py", line 532, in get_clusters
    'handle': pickle.loads(handle),
AttributeError: Can't get attribute 'CloudVmRayResourceHandle' on <module 'sky.backends.cloud_vm_ray_backend' from '/Users/zongheng/anaconda/envs/py38/lib/python3.8/site-packages/sky/backends/cloud_vm_ray_backend.py'>
```

**Comment by iojw** [comment] 2023-03-08 03:57
@romilbhardwaj I'd like to understand this better. Based on our current design, if we modify any pickled class (such as `Resources`), then we should correspondingly update the `__setstate__` and `_VERSION` field version to properly handle unpickling types that were created with an older version. If these fields are updated correctly, then there should be no errors when pickling / unpickling. Do you have any more details regarding what the issue is with pickling / unpickling?

This is an issue of how to deal with changing schemas with serialization, and I don't think that moving to a different serde method would solve this. Even if we were to use json, the issue of how to load old json into a modified schema still exists.

**Comment by Michaelvll** [comment] 2023-03-08 04:24
One problem with pickle is that it may not be compatible when we change the python version. For example, if the sky was running in python 3.10 and now we change the python version to 3.7, it is likely the unpickling will fail, as `pickle` only guarantees backward compatibility, and there is a protocol jump from 3.7 to 3.8.

**Comment by Michaelvll** [comment] 2023-03-08 04:26
> Ran into this again after upgrading from python 3.7 to 3.8 in a new conda environment. `sky status` would fail at `pickle.loads()` due to version mismatch:
> 
> ```
> ...
>   File "/Users/zongheng/anaconda/envs/py38/lib/python3.8/site-packages/sky/backends/backend_utils.py", line 2244, in get_clusters
>     records = global_user_state.get_clusters()
>   File "/Users/zongheng/anaconda/envs/py38/lib/python3.8/site-packages/sky/global_user_state.py", line 532, in get_clusters
>     'handle': pickle.loads(handle),
> AttributeError: Can't get attribute 'CloudVmRayResourceHandle' on <module 'sky.backends.cloud_vm_ray_backend' from '/Users/zongheng/anaconda/envs/py38/lib/python3.8/site-packages/sky/backends/cloud_vm_ray_backend.py'>
> ```

Actually, this problem is not related to the pickle, but the recent change for the mypy. If you were switching SkyPilot from the later version back to the earlier one before the mypy PR was merged, this problem occurs, which will not affect our user, as their SkyPilot version will only go forward.

**Comment by iojw** [comment] 2023-03-08 04:33
@Michaelvll I see, that makes sense. In that case, how about we fix the pickle protocol version then? Currently, we use the [default protocol](https://docs.python.org/3/library/pickle.html#pickle.DEFAULT_PROTOCOL) which was changed to 4 for Python 3.8. We can fix it at 4 to ensure that the same issue does not occur again. 

Apart from that, I believe the original issue may be caused by not updating the `__setstate__` and `_VERSION` fields properly.

**Comment by Michaelvll** [comment] 2023-03-08 06:48
> @Michaelvll I see, that makes sense. In that case, how about we fix the pickle protocol version then? Currently, we use the [default protocol](https://docs.python.org/3/library/pickle.html#pickle.DEFAULT_PROTOCOL) which was changed to 4 for Python 3.8. We can fix it at 4 to ensure that the same issue does not occur again.

Setting the protocol to 4 sounds good to me. However, it still does not solve the problem mentioned in https://github.com/skypilot-org/skypilot/issues/1605#issue-1538412309. The current workaround for that is to have define a variable in `sky.cloud.__init__`, such that `Cloud = new_module.Cloud`.

**Comment by iojw** [comment] 2023-03-08 09:45
@Michaelvll That seems like the best solution to me for dealing with changing module paths, if we have to deal with it in the future. An alternative would also be to write a custom [`Unpickler`](https://docs.python.org/3/library/pickle.html#pickle.Unpickler.find_class) that returns the appropriate class.

**Comment by iojw** [comment] 2023-03-10 19:56
Closing this issue because:
- `pickle` is working as expected. When changing the schema of the handle, we need to update the `_VERSION` and `__setstate__` fields of the class to ensure that that `pickle` correctly unpickles older versions.
- The issue with changing module paths can be dealt with using the workarounds mentioned above.
- We considered using a separate serde such as `json`, but the issue with `json` is that the issue of how to deal with changing object schemas still exists. There is no built-in method to deal with this issue within the `json` module.

**Closed by iojw** 2023-03-10 19:56 UTC
Labels: P0, friction-log
