### ISSUE TITLE
Initializing Azure instances is very slow

### ISSUE THREAD

**Issue by suquark** [skypilot-org/skypilot#328] opened 2022-02-15 03:33 UTC
It takes me 14min to spin up a cluster with 2 cpu nodes.

The most time consuming part is installing pip packages, especially `azure-cli`. This may be addressed by releasing images with `azure-cli` pre-installed.

**Comment by concretevitamin** [comment] 2022-08-25 16:17
I tried revisiting this issue briefly. For a cpunode:

- Launching using Azure web console: **about 1.5 min** from "create" button to being able to SSH in.  Same VM image, region.  Only diff being using an existing resource group.
- Launching using `sky launch` (which means ray autoscaler, which means Azure python SDK): super slow, **~9 min**.  Every step is slower than console.

I hacked the template by using the same resource group per region -- no speedup.

So the root cause seems to be Azure's python SDK being much slower than their console. We can take a deeper look.


Typical output
- ~4-5min from create to SSH
- ~4min to install runtime
```
I 08-25 08:58:46 cloud_vm_ray_backend.py:892] To view detailed progress: tail -n100 -f /Users/zongheng/sky_logs/sky-2022-08-25-08-58-44-664631/provision.log
I 08-25 08:58:46 cloud_vm_ray_backend.py:1096] Launching on Azure eastus ()
I 08-25 09:01:53 cloud_vm_ray_backend.py:1131] Retrying head node provisioning due to head fetching timeout.
I 08-25 09:03:40 log_utils.py:45] Head node is up.
I 08-25 09:07:41 cloud_vm_ray_backend.py:984] Successfully provisioned or found existing VM.
```

**Comment by romilbhardwaj** [comment] 2022-08-25 17:10
> So the root cause seems to be Azure's python SDK being much slower than their console. We can take a deeper look.

Might be good to verify this hypothesis by using their pure python SDK (without ray autoscaler) to provision a VM and measure time. Here's an [example](https://docs.microsoft.com/en-us/azure/developer/python/sdk/examples/azure-sdk-example-virtual-machines?tabs=cmd).

**Comment by infwinston** [comment] 2023-05-13 00:29
We should also keep this one open unless we are satisfied with the speed with Azure.

**Comment by WesleyYue** [comment] 2024-06-05 17:02
Can this be re-opened? Still very slow today

**Comment by WesleyYue** [comment] 2024-07-05 15:07
Related https://github.com/skypilot-org/skypilot/issues/3695

**Comment by Michaelvll** [comment] 2024-07-15 20:51
This issue should be mitigated by #3704. Closing for now.

**Closed by Michaelvll** 2024-07-15 20:51 UTC
Labels: enhancement
