### ISSUE TITLE
sky autostop doesn't happen

### ISSUE THREAD

**Issue by lhqing** [skypilot-org/skypilot#1306] opened 2022-10-27 00:41 UTC
Hi Skyteam,

**Problem**
I am trying to use the `sky autostop` feature on a VM running `jupyter lab`. As suggested by @Michaelvll , I used this command to run jupyter in background
`nohup jupyter-lab --LabApp.token='' --no-browser --port 8898 > ~/jupyter.log 2>&1 &`
But the sky VM did not autostop 

**sky YAML**
```
# jupyter.yaml

name: test

resources:
  cloud: gcp
  instance_type: n2d-standard-8
  region: us-west1
  disk_size: 64

file_mounts:
  /rs2:
    source: gs://.../
    mode: MOUNT
  /data:
    source: gs://.../
    mode: MOUNT
  /cemba:
    source: gs://.../
    mode: MOUNT
  /ref:
    source: gs://.../
    mode: MOUNT
  /home/hanliu:
    source: gs://.../
    mode: MOUNT

setup: |
  if [ -f /opt/conda/bin/mamba ]
  then
    echo "Skip setup"
  else
    conda install mamba -y -n base -c conda-forge
    pip install --upgrade pip
    gsutil cp gs://ecker-hanqing-wmb-us-west1/wmb/sky/env.yaml ./
    mamba env update -f env.yaml
    rm env.yaml
  fi

run: |
  cd ~/sky_workdir
  nohup jupyter-lab --LabApp.token='' --no-browser --port 8898 > ~/jupyter.log 2>&1 &
```

**Logs**

- **Launch VM**
```
# hanqingliu @ belmontezf in ~/src/whole_mouse_brain/gcp/sky on git:main x [17:21:09]
$ sky launch -c test -y sky-test-autostop.yaml
Task from YAML spec: sky-test-autostop.yaml
Running task on cluster test...
I 10-26 17:21:17 cloud_vm_ray_backend.py:903] To view detailed progress: tail -n100 -f /Users/hanqingliu/sky_logs/sky-2022-10-26-17-21-17-072173/provision.log
I 10-26 17:21:17 cloud_vm_ray_backend.py:744] Cluster 'test' (status: INIT) was previously launched in GCP (us-west1). Relaunching in that region.
I 10-26 17:21:18 authentication.py:240] OS Login is enabled for GCP project prod-635e. Running additional authentication steps.
I 10-26 17:21:20 cloud_vm_ray_backend.py:1152] Launching on GCP us-west1 (us-west1-b)
I 10-26 17:22:10 log_utils.py:45] Head node is up.
I 10-26 17:23:02 cloud_vm_ray_backend.py:996] Successfully provisioned or found existing VM.
I 10-26 17:23:04 cloud_vm_ray_backend.py:2894] Processing 5 storage mounts.
I 10-26 17:23:04 backend_utils.py:1004] Mounting (to 1 node): gs://ecker-cemba-rs2/ -> /rs2
I 10-26 17:23:07 backend_utils.py:1004] Mounting (to 1 node): gs://ecker-rachel-analysis/ -> /data
I 10-26 17:23:09 backend_utils.py:1004] Mounting (to 1 node): gs://ecker-hanqing-wmb-us-west1/ -> /cemba
I 10-26 17:23:11 backend_utils.py:1004] Mounting (to 1 node): gs://ecker-hanqing-reference/ -> /ref
I 10-26 17:23:13 backend_utils.py:1004] Mounting (to 1 node): gs://ecker-hanqing-analysis/ -> /home/hanliu
I 10-26 17:23:14 cloud_vm_ray_backend.py:1999] Running setup on 1 node.
Skip setup
I 10-26 17:23:18 cloud_vm_ray_backend.py:2002] Setup completed.
I 10-26 17:23:24 cloud_vm_ray_backend.py:2067] Job submitted with Job ID: 2
I 10-27 00:23:26 log_lib.py:385] Start streaming logs for job 2.
INFO: Tip: use Ctrl-C to exit log streaming (task will not be killed).
INFO: Waiting for task resources on 1 node. This will block if the cluster is full.
INFO: All task resources reserved.
INFO: Reserved IPs: ['10.138.0.25']

Shared connection to 34.83.22.217 closed.
I 10-26 17:23:27 cloud_vm_ray_backend.py:2080] Job ID: 2
I 10-26 17:23:27 cloud_vm_ray_backend.py:2080] To cancel the job:	sky cancel test 2
I 10-26 17:23:27 cloud_vm_ray_backend.py:2080] To stream the logs:	sky logs test 2
I 10-26 17:23:27 cloud_vm_ray_backend.py:2080] To view the job queue:	sky queue test
I 10-26 17:23:27 cloud_vm_ray_backend.py:2189]
I 10-26 17:23:27 cloud_vm_ray_backend.py:2189] Cluster name: test
I 10-26 17:23:27 cloud_vm_ray_backend.py:2189] To log into the head VM:	ssh test
I 10-26 17:23:27 cloud_vm_ray_backend.py:2189] To submit a job:		sky exec test yaml_file
I 10-26 17:23:27 cloud_vm_ray_backend.py:2189] To stop the cluster:	sky stop test
I 10-26 17:23:27 cloud_vm_ray_backend.py:2189] To teardown the cluster:	sky down test
NAME        LAUNCHED     RESOURCES                STATUS   AUTOSTOP  COMMAND
test        23 secs ago  1x GCP(n2d-standard-8)   UP       -         sky launch -c test -y sky...
sl-jupyter  1 hr ago     1x GCP(n2d-highmem-96)   UP       -         sky launch -c sl-jupyter -y...
jupyter     1 hr ago     1x GCP(n2d-standard-32)  UP       1 min     sky launch -c jupyter -y ...
l-jupyter   2 hrs ago    1x GCP(n2d-standard-96)  STOPPED  -         sky launch -c l-jupyter -y...

You have 1 clusters with autostop scheduled. Refresh statuses with: `sky status --refresh`.
(base)
```

- **Set autostop "test" cluster**
```
# hanqingliu @ belmontezf in ~/src/whole_mouse_brain/gcp/sky on git:main x [17:23:27]
$ sky autostop test
Scheduling auto-stop on 1 cluster: test. Proceed? [Y/n]: Y
Scheduling auto-stop on cluster 'test'...done
  The cluster will be stopped after 5 minutes of idleness.
  To cancel the autostop, run: sky autostop test --cancel
Scheduling auto-stop on 1 cluster ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
(base)
```

- **Still not stop after 10mins**
```
# hanqingliu @ belmontezf in ~/src/whole_mouse_brain/gcp/sky on git:main x [17:24:50]
$ sky status -r
NAME        LAUNCHED     RESOURCES                STATUS   AUTOSTOP  COMMAND
test        42 secs ago  1x GCP(n2d-standard-8)   UP       5 min     sky launch -c test -y sky...
sl-jupyter  1 hr ago     1x GCP(n2d-highmem-96)   UP       -         sky launch -c sl-jupyter -y...
jupyter     2 hrs ago    1x GCP(n2d-standard-32)  UP       1 min     sky launch -c jupyter -y ...
l-jupyter   2 hrs ago    1x GCP(n2d-standard-96)  STOPPED  -         sky launch -c l-jupyter -y...

You have 2 clusters with autostop scheduled. Refresh statuses with: `sky status --refresh`.
(base)
```

**Comment by lhqing** [comment] 2022-10-27 00:45
There is error info in skylet.log
[skylet.log](https://github.com/skypilot-org/skypilot/files/9874749/skylet.log)

**Comment by lhqing** [comment] 2022-10-27 00:46
```
$ sky queue test
Fetching and parsing job queue...

Job queue of cluster test
ID  NAME  SUBMITTED    STARTED      DURATION  RESOURCES     STATUS     LOG
2   test  51 secs ago  46 secs ago  < 1s      1x [CPU:0.5]  SUCCEEDED  ~/sky_logs/sky-2022-10-26-17-21-17-072173
1   test  1 hr ago     1 hr ago     < 1s      1x [CPU:0.5]  SUCCEEDED  ~/sky_logs/sky-2022-10-26-16-00-50-068299
```

**Comment by lhqing** [comment] 2022-10-27 00:47
```
hanliu_salk_edu@ray-test-head-5b9ba124-compute:~$ ls -hl
total 28K
-rw-r--r-- 1 hanliu_salk_edu hanliu_salk_edu 3.8K Oct 27 00:23 jupyter.log
-rw------- 1 hanliu_salk_edu hanliu_salk_edu  11K Oct 27 00:21 ray_bootstrap_config.yaml
lrwxrwxrwx 1 hanliu_salk_edu hanliu_salk_edu   63 Oct  6 05:32 ray_bootstrap_key.pem -> '/Users/hanqingliu/Google Drive/My Drive/work/sky_status/sky-key'
drwxr-xr-x 4 hanliu_salk_edu hanliu_salk_edu 4.0K Oct 27 00:23 sky_logs
drwxr-xr-x 2 hanliu_salk_edu hanliu_salk_edu 4.0K Oct 26 23:08 sky_workdir
```

**Comment by Michaelvll** [comment] 2022-10-27 00:58
After discussing offline, we figured out that the problem is that, the `ray up` directly upload the soft link for the private key to the remote cluster, instead of uploading the contents. That causes the autostop to fail to `ray up` again with the `~/ray_bootstrap_key.pem` on the VM. 

It is worth trying to use hard link for the `sky-key` instead of the soft link on the local laptop. In that way, the upload should be correct.

**Comment by lhqing** [comment] 2022-10-27 01:27
@Michaelvll Thanks! I can confirm the autostop works once I fix the `sky-key` issue. Feel free to close this issue.

**Comment by Michaelvll** [comment] 2022-10-27 03:31
Nice! Thanks for filing the issue and testing it out @lhqing! We should probably have a note for it in the doc, when we are going to officially support sharing the states in `~/.sky/` across multiple machines. Closing this for now. ; )

**Closed by Michaelvll** 2022-10-27 03:31 UTC
