### ISSUE TITLE
[request] Support exposing a port from a Skypilot VM

### ISSUE THREAD

**Issue by parasj** [skypilot-org/skypilot#1487] opened 2022-12-03 01:42 UTC
SSH forwarding is the only supported way to expose a port to the world in Skypilot [today](https://skypilot.readthedocs.io/en/latest/examples/gpu-jupyter.html). However, I need public access to the VM without SSH forwarding.

The task YAML should support a ports field:
```
ports:
  - 8080
```

I currently must manually add the port via the AWS EC2 console.

**Comment by romilbhardwaj** [comment] 2022-12-03 01:57
Thanks for the report @parasj! This is also tracked in #1255.

As a temporary workaround, if you're on AWS you can leverage the fact that skypilot reuses security groups. Thus, youcan configure the ports needed on that security group once, and all future VMs will have that port open. For example in #1255, I opened port 8888 and then I could access jupyter on all ips.

**Comment by parasj** [comment] 2022-12-03 02:13
Thanks Romil, does this need to be applied to every SG across regions? I can probably workaround this with a script to update SGs if the security group name is consistent across regions.

**Comment by romilbhardwaj** [comment] 2022-12-03 02:32
I think it should be the same security group, but let me confirm. I can get back to you in a day or so. cc @Michaelvll

**Comment by Michaelvll** [comment] 2022-12-03 04:50
Yes, it should be the same name across the region. The name will look like `sky-sg-<hash>`

**Comment by romilbhardwaj** [comment] 2022-12-15 05:46
Closing this since it's a duplicate of #1255.

**Closed by romilbhardwaj** 2022-12-15 05:46 UTC
