### ISSUE TITLE
`pip install skypilot` fails inside `docker run -it continuumio/miniconda3` (Apple M1)

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#1490] opened 2022-12-05 11:07 UTC
```
» docker run -it continuumio/miniconda3

<inside>
$ pip install skypilot
...
Requirement already satisfied: cryptography in /opt/conda/lib/python3.9/site-packages (from skypilot) (36.0.0)
ERROR: Cannot install skypilot==0.1.1, skypilot==0.1.2, skypilot==0.2.0 and skypilot==0.2.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    skypilot 0.2.1 depends on ray[default]<=1.13.0 and >=1.9.0
    skypilot 0.2.0 depends on ray[default]<=1.13.0 and >=1.9.0
    skypilot 0.1.2 depends on ray[default]<=1.13.0 and >=1.9.0
    skypilot 0.1.1 depends on ray[default]>=1.9.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

**Comment by Michaelvll** [comment] 2022-12-05 20:49
I tried it on my macbook with Intel CPU and it seems working for me. I am guessing the problem is caused by `ray<=1.13.0` not supporting the M1 chip. Could you confirm?

**Comment by concretevitamin** [comment] 2022-12-06 00:37
Yes, this was run on Apple M1. Tried:
- https://docs.ray.io/en/releases-1.13.0/ray-overview/installation.html#m1-mac-apple-silicon-support
- or [our note](https://skypilot.readthedocs.io/en/latest/getting-started/installation.html) of `conda install grpcio=1.43.0`

Didn't resolve this issue.

**Comment by romilbhardwaj** [comment] 2022-12-16 01:40
@pounde also ran into this recently. From slack:

> What method did you use to install SkyPilot? It is failing on a Ray dependency. Oddly enough pip can't find Ray...strange.

> So it appears it may be because I am on a Mac...strange as that's the entire selling point of Docker. I spun up an AWS instance (using Sky of course) and tried it...works fine. Not sure how to get around that but at least I know the cause. Apologies for these nuisance reports.

**Comment by pounde** [comment] 2022-12-16 14:49
That is correct. I ran into the same issue yesterday. While the planned deployment is on Linux this is a challenge for development. I am running Apple M1 Max. Identical error as @concretevitamin.

**Comment by pounde** [comment] 2022-12-16 22:20
I was able to side-step the problem by passing `--platform linux/amd64` in the `docker run` command. Probably worth closing this as it's not a SkyPilot issue.

**Comment by pounde** [comment] 2022-12-17 00:43
On further testing, this does not resolve the underlying issue that Sky does not work on M1 machines. I get the following when running `sky check`:
`(base) root@1c590d176a7c:/# sky check
SkyPilot collects usage data to improve its services. `setup` and `run` commands are not collected to ensure privacy.
Usage logging can be disabled by setting the environment variable SKYPILOT_DISABLE_USAGE_COLLECTION=1.
Checking credentials to enable clouds for SkyPilot.
  Checking AWS...I 12-17 00:41:02 aws_catalog.py:47] Fetching availability zones mapping for AWS...`

**Comment by romilbhardwaj** [comment] 2022-12-17 01:19
My hunch is this is related to the `ray.init()` we require for fetching AWS catalogs.:
https://github.com/skypilot-org/skypilot/blob/e9b378e63296e0a545bc83e6f54e05e4a0afd765/sky/clouds/service_catalog/aws_catalog.py#L47-L51

I see warnings on windows + WSL at the same step:
```
Fetching availability zones mapping for AWS...
E1217 06:42:09.186705900     223 socket_utils_common_posix.cc:223] check for SO_REUSEPORT: {"created":"@1671239529.186661500","description":"Protocol not available","errno":92,"file":"external/com_github_grpc_grpc/src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":202,"os_error":"Protocol not available","syscall":"getsockopt(SO_REUSEPORT)"}
... <proceeds normally>
```
cc @Michaelvll 

I'll get hold of a M1 machine and try to debug this.

**Comment by pounde** [comment] 2022-12-17 03:59
Roger. It's worth mentioning that it SkyPilot works as advertised outside docker...inside the container is the problem.

**Comment by romilbhardwaj** [comment] 2022-12-19 08:40
Haven't had luck getting a M1 machine to debug this. I tried mac2 instances on EC2, but setting up docker on those is practically impossible through just ssh - you need [some kind of remote desktop](https://stackoverflow.com/a/65126778) (vnc/ard) to launch the docker app. Apple Remote Desktop is not available for linux/windows and [enabling open VNC protocols again requires a GUI](https://support.apple.com/en-in/guide/remote-desktop/apdbed09830/mac). Can someone with a M1 mac look at this? cc @concretevitamin 

These issues [[1]](https://github.com/ray-project/ray/issues/28103)[[2]](https://github.com/ray-project/ray/issues/25300) seem related.

**Comment by pounde** [comment] 2022-12-20 12:29
...it's probably worth mentioning that I am yet to get it working on a remote setup. It may be more
Blocking than I initially thought.

**Comment by pounde** [comment] 2023-01-10 18:55
Per this issue: https://github.com/ray-project/ray/issues/28103, it may be resolved. I haven't gotten around to checking this yet though.

**Comment by iojw** [comment] 2023-03-08 04:58
I just tested this on a M1 Mac (13.1) and got it working with the following commands:
`docker run -it continuumio/miniconda3`
`conda install -c conda-forge gcc`
`pip install skypilot`

`gcc` is required by the `psutil` package. I think this issue is resolved.

**Closed** 2023-03-10 18:47 UTC
Labels: P0

**Comment by Michaelvll** [comment] 2023-03-10 18:49
Oh, I think the main reason this is solved is that ray has built the wheel for ARM64 for the latest ray version ([here](https://github.com/ray-project/ray/issues/28103), and we recently allowed the local ray version to be the latest one, but it is great that it is solved. : )
